imly/urls.py
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from imly.models import Product, Store, Category, Location
from imly.views.stores import OrderList, StoreList, StoreCreate, StoreDetail, StoreEdit, StoreInfoDetail, home_page, why_open_your_shop, contact_us, faqs, what_is_imly, wrong_location, status, update_store_order, no_city, not_in_city, one_step_checkout, CreateStore, ManageStore, upload_images
from imly.views.products import SpecialList, ProductReview, ProductList, ProductCreate, ProductDelete, ProductDetail, ProductEdit, ProductsByAccount, coming_soon,sort_product,activate_product,special_event,unsubscribe_event,wish_product,wishlist,remove_product,remove_product,upload_product_images
from imly.views.profile import ProfileInfo,ProfileCreate,EditProfile, ChefProfile, ProfileList
from imly.views.places import set_location, unset_location, set_city, set_delivery, set_pick_up
from imly.views.orders import UserOrders, StoreOrders, update_store_orders_for_order,update_cart,change_quantity,change_quantity_text
from imly.views.tags import add_tag, remove_tag
from imly.views.recipes import RecipeList, RecipeDetail, EditRecipe, AddRecipe
from imly.sitemaps import all_sitemaps as sitemaps
from plata.contact.models import Contact
from plata.discount.models import Discount
from plata.shop.models import Order
from plata.shop.views import Shop
from plata.shop.forms import BaseCheckoutForm
from patches import patched_base_checkout_form_clean

BaseCheckoutForm.clean = patched_base_checkout_form_clean

shop = Shop(
    contact_model=Contact,
    order_model=Order,
    discount_model=Discount,
    default_currency= "INR",
    )

product_info = {
    "queryset" : Product.objects.all(),
    "template_name" : "product_list.html"
}

store_info = {
    "queryset" : Store.objects.all(),
    "template_name" : "store_list.html"
}

category_info = {
    "queryset" : Category.objects.all(),
    "template_name":"category_list.html"
}

location_info = {
    "queryset" : Location.objects.all(),
    "template_name":"location_list.html"
}

urlpatterns = patterns('',

    url(r"^$", home_page, name="imly_landing_page"),
    url(r"^give_us_tip/$", "imly.views.profile.give_us_tip",name="imly_give_us_tip"),
    url(r"^login-x/$", "imly.views.profile.modal_login", name="imly_modal_login"),
    url(r"^signup-x/$", "imly.views.profile.modal_signup", name="imly_modal_signup"),
    url(r"^why-join-imly/$", why_open_your_shop, name="why_open_your_shop"),
    url(r"^contact-us/$", contact_us, name="imly_contact_us"),
    url(r"^faqs/$", faqs, name="imly_faqs"),
    url(r"^what-is-imly/$", what_is_imly, name="what_is_imly"),
    url(r"^shops/$", StoreList.as_view(), name="imly_store_list"),
    url(r"^chefs/$", ProfileList.as_view(), name="imly_profiles"),
    url(r"^chefs/(?P<slug>[-\w]+)/$", ChefProfile.as_view(), name="chef_profile"),
    url(r"^specials/(?P<slug>[-\w]+)/$", SpecialList.as_view(), name='imly_specials'),
    url(r"^account/store/create/$", login_required(StoreCreate.as_view()), name ="imly_store_create"),
    url(r"^account/store/details/$", login_required(StoreInfoDetail.as_view()), name ="imly_store_info"),
    url(r"^account/my-profile/$",login_required(ProfileInfo.as_view()),name='imly_my_profile'),
    url(r"^account/create-profile/$",login_required(ProfileCreate.as_view()),name='imly_create_profile'),
    url(r"^account/edit-profile/$",login_required(EditProfile.as_view()),name='imly_profile_edit'),
    url(r"^account/orders/$",login_required(UserOrders.as_view()),name='imly_user_orders'),
    url(r"^account/store/edit/$", login_required(StoreEdit.as_view()), name="imly_store_edit"),
    url(r"^account/store/orders/$", login_required(StoreOrders.as_view()), name="imly_store_orders"),
    url(r"^account/store/sort-product/$","imly.views.products.sort_product",name="imly_store_sort_product"),
    url(r"^coming-soon/$", coming_soon, name="imly_coming_soon"),
    url(r"^no-such-place/$", wrong_location, name="wrong_location"),
    url(r"^will-be-there-soon/$", no_city, name="imly_dont_see_city"),
    url(r"^not-in-city/$", not_in_city, name="not_in_city"),
    url(r"^special_event/(?P<event_slug>[-\w]+)/(?P<product_slug>[-\w]+)/$",special_event,name="imly_special_event"),
    url(r"^unsubscribe_event/(?P<event_slug>[-\w]+)/(?P<product_slug>[-\w]+)/$",unsubscribe_event,name="imly_unsubscribe_event"),

)

urlpatterns += patterns('',

    url(r"^set_location/$", set_location, name="imly_filter_by_place"),
    url(r"^unset_location/$", unset_location, name="unset_location"),
    url(r'^set_city/(?P<slug>[-\w]+)/$', set_city, name='imly_set_city'),
    url(r"^add-tag/(?P<slug>[-\w]+)/$", add_tag, name="add_tag"),
    url(r"^remove-tag/(?P<slug>[-\w]+)/$", remove_tag, name="remove_tag"),
    url(r"^delivery/$", set_delivery, name="set_delivery"),
    url(r"^pick-up/$", set_pick_up, name="set_pick_up"),
    #url(r"^places/$", ListView.as_view(**location_info), name="imly_place_list" ),
    #url(r"^places/(?P<place_slug>[-\w]+)/stores/$", StoresByPlace.as_view(), name="imly_stores_by_place"),
    #url(r"^places/(?P<place_slug>[-\w]+)/products/$", "products_by_place", name="imly_products_by_place"),

)

urlpatterns += patterns('',
    url(r"^upload/images/$",upload_images,name="upload_images"),
    url(r"^upload/images/(?P<slug>[-\w]+)/$",upload_product_images,name="upload_product_images"),
    #url(r"^upload/cover/$",upload_store_cover,name="upload_store_logo"),
)


urlpatterns += patterns('',

    url(r"^food/$", ProductList.as_view(), name="imly_product_list"),
    url(r"^review/$", ProductReview.as_view(), name="submit_product_review"),
    url(r"^account/store/status/$", "imly.views.stores.status" , name="imly_store_status"),



)

urlpatterns += patterns('',

    #url(r"^categories/$", ListView.as_view(**category_info), name="imly_category_list" ),
    url(r"^categories/(?P<category_slug>[-\w]+)/chefs/$", StoreList.as_view(), name="imly_stores_by_category"),
    url(r"^categories/(?P<category_slug>[-\w]+)/food/$", ProductList.as_view(), name="imly_products_by_category"),
)


urlpatterns += patterns('',
    url(r"^account/store/products/add/$", login_required(ProductCreate.as_view()), name="imly_product_add"),
    url(r"^account/store/products/(?P<pk>\d+)/edit$", login_required(ProductEdit.as_view()), name="imly_product_edit"),
    #url(r"^account/store/products/(?P<product_id>\d+)/delete/$", "imly.views.products.delete_product", name="imly_product_delete"),
    url(r"^account/store/products/(?P<pk>\d+)/delete/$", login_required(ProductDelete.as_view()), name="imly_product_delete"),
    url(r"^account/store/products/(?P<product_id>\d+)/activate/$", "imly.views.products.activate_product", name="imly_product_activate"),
    url(r"^account/store/products/$", login_required(ProductsByAccount.as_view()), name="imly_store_products" ),

)
urlpatterns += patterns('',
    url(r"^shop/", include(shop.urls), name="imly_shop"),
    url(r"^shop/add/(?P<store_slug>[-\w]+)/(?P<product_slug>[-\w]+)/$", "imly.views.stores.add_order", name="imly_add_order"),
)

urlpatterns += patterns('', url(r'^search/(?P<search_item>food|store)', 'imly.views.products.search', name='imly_search'))

urlpatterns += patterns('',
    url(r"^recipes/$", RecipeList.as_view(), name = "imly_recipe_list"),
    url(r"^account/store/recipe/add/(?P<slug>[-\w]+)/$", AddRecipe.as_view(), name = "imly_recipe_add"),
    url(r"^account/store/recipe/edit/(?P<slug>[-\w]+)/$", EditRecipe.as_view(), name = "imly_recipe_edit"),
    url(r"^recipe/(?P<slug>[-\w]+)/$", RecipeDetail.as_view(), name="imly_recipe_detail")
)

urlpatterns += patterns('',
    url(r"^accounts/stores/create/$", CreateStore.as_view(), name="create_store"),
    url(r"^accounts/stores/$", ManageStore.as_view(), name="manage_store"),
                        )

urlpatterns += patterns('',
    url(r"^checkout/$", one_step_checkout, name="imly_one_step_checkout"),
    url(r'^storeorder$', update_store_order, name='update_store_order'),
    url(r'^order/(?P<pk>\d+)/update-store-orders/$', update_store_orders_for_order, name='update_store_orders_for_order'),
    url(r'^orderitem/remove/$',update_cart,name='update_cart'),
    url(r'^orderitem/change_quantity/(?P<change>up|down)/$',change_quantity,name='change_quantity'),
    url(r'^orderitem/change_quantity/text/$',change_quantity_text,name='change_quantity_text'),
    url(r'^wish_product/$',wish_product,name='wishlist'),
    url(r'^wish_remove_product/$',remove_product,name='remove_wish'),
    url(r'^favourites/$',wishlist,name='show_wishlist'),
    url(r'^sitemap.xml$', 'django.contrib.sitemaps.views.index', {'sitemaps': sitemaps}),
    url(r'^sitemap-(?P<section>.+)\.xml$', 'django.contrib.sitemaps.views.sitemap', {'sitemaps': sitemaps}),
    url(r"^(?P<slug>[-\w]+)/$", StoreDetail.as_view() , name="imly_store_detail"),
    url(r"^(?P<store_slug>[-\w]+)/(?P<slug>[-\w]+)/$", ProductDetail.as_view(), name="imly_product_detail"),
)

imly_project/urls.py
from django.conf.urls import patterns, include, url
from django.views.generic.base import TemplateView
from imly_project import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'imly_project.views.home', name='home'),
    # url(r'^imly_project/', include('imly_project.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^nimda/', include(admin.site.urls)),
    #url(r'^community/', include('forum.urls')),
    url(r'^tracking/', include('tracking.urls')),
    url(r'^facestore/', include('facestore.urls')),
    url(r"", include("allauth.urls")),
    url(r"", include("imly.urls")),
    url(r'^robots\.txt$', TemplateView.as_view(template_name='robots.txt', content_type='text/plain')),
)

if settings.DEBUG:
    urlpatterns += patterns('',
        url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {
            'document_root': settings.MEDIA_ROOT,
        }),
   )

plata/shop/forms.py
from django import forms
from django.contrib import auth
from django.contrib.auth.models import User
from django.utils.translation import ugettext_lazy as _

from plata.shop import signals


class BaseCheckoutForm(forms.ModelForm):
    """
    Needs self.request
    """

    def __init__(self, *args, **kwargs):
        self.shop = kwargs.pop('shop')
        self.request = kwargs.pop('request')

        super(BaseCheckoutForm, self).__init__(*args, **kwargs)

    def clean(self):
        data = super(BaseCheckoutForm, self).clean()

        email = data.get('email')
        create_account = data.get('create_account')

        if email:
            users = list(User.objects.filter(email=email))

            if users:
                if self.request.user not in users:
                    if self.request.user.is_authenticated():
                        self._errors['email'] = self.error_class([
                            _('This e-mail address belongs to a different account.')])
                    else:
                        self._errors['email'] = self.error_class([
                            _('This e-mail address might belong to you, but we cannot know for sure because you are not authenticated yet.')])

        return data

    def save(self):
        """
        Save the order, create or update the contact information (if available)
        and return the saved order instance
        """
        order = super(BaseCheckoutForm, self).save(commit=False)
        contact = self.shop.contact_from_user(self.request.user)

        if contact:
            order.user = contact.user
        elif self.request.user.is_authenticated():
            order.user = self.request.user

        if (self.cleaned_data.get('create_account') and not contact) or (
                not contact and self.request.user.is_authenticated()):
            password = None
            email = self.cleaned_data.get('email')

            if not self.request.user.is_authenticated():
                password = User.objects.make_random_password()
                user = User.objects.create_user(email, email, password)
                user = auth.authenticate(username=email, password=password)
                auth.login(self.request, user)
            else:
                user = self.request.user

            contact = self.shop.contact_model(user=user)
            order.user = user

            signals.contact_created.send(sender=self.shop, user=user,
                contact=contact, password=password)

        order.save()

        if contact:
            contact.update_from_order(order, request=self.request)
            contact.save()

        return order


class DiscountForm(forms.Form):
    code = forms.CharField(label=_('code'), max_length=30, required=False)

    def __init__(self, *args, **kwargs):
        self.order = kwargs.pop('order')
        self.discount_model = kwargs.pop('discount_model')
        request = kwargs.pop('request') # Unused
        shop = kwargs.pop('shop') # Unused

        super(DiscountForm, self).__init__(*args, **kwargs)

    def clean_code(self):
        code = self.cleaned_data.get('code')
        if not code:
            return self.cleaned_data

        try:
            discount = self.discount_model.objects.get(code=code)
        except self.discount_model.DoesNotExist:
            raise forms.ValidationError(_('This code does not validate'))

        discount.validate(self.order)
        self.cleaned_data['discount'] = discount
        return code

    def save(self):
        """
        Save the discount (or do nothing if no discount code has been given)
        """
        if 'discount' in self.cleaned_data:
            self.cleaned_data['discount'].add_to(self.order)


class ConfirmationForm(forms.Form):
    terms_and_conditions = forms.BooleanField(
        label=_('I accept the terms and conditions.'),
        required=True)

    def __init__(self, *args, **kwargs):
        self.order = kwargs.pop('order')
        self.request = kwargs.pop('request')
        self.shop = kwargs.pop('shop')
        self.payment_modules = self.shop.get_payment_modules(self.request)

        super(ConfirmationForm, self).__init__(*args, **kwargs)

        self.fields['payment_method'] = forms.ChoiceField(
            label=_('Payment method'),
            choices=[('', '----------')] + [
                (m.__module__, m.name) for m in self.payment_modules],
            )

    def clean(self):
        data = super(ConfirmationForm, self).clean()
        self.order.validate(self.order.VALIDATE_ALL)
        return data

    def process_confirmation(self):
        """
        Process the successful order submission
        """
        self.order.update_status(self.order.CONFIRMED, 'Confirmation given')
        signals.order_confirmed.send(sender=self.shop, order=self.order)

        payment_module = dict((m.__module__, m)
            for m in self.payment_modules)[self.cleaned_data['payment_method']]

        return payment_module.process_order_confirmed(self.request, self.order)

imly/views.py
# Create your views here.

imly/views/contact.py
from imly.forms import GiveTipForm
from django.views.generic.edit import FormView

class TipView(FormView):
    template_name = "contact.html"
    form_class = GiveTipForm
    success_url = "/thanks/"
    
    def form_valid(self,form):
        form.send_email()
        return super(TipView, self).form_valid(form)

imly/views/shop.py
from plata.shop.views import Shop

class ImlyShop(Shop):

    def get_context(self, request, context, **kwargs):
        """
        Helper method returning a context dict. Override this if you
        need additional context variables.
        """
        self.ctx = {
            'base_template': self.base_template,
            }
        self.ctx.update(context)
        self.ctx.update(kwargs)
        return self.ctx

imly/views/tags.py
from imly.models import Tag
from django.shortcuts import get_object_or_404, redirect, render

def add_tag(request, slug):
    if request.session.get('tags',None):
        tags = request.session['tags']
        tags.append(slug)
        request.session['tags'] = tags
    else:
        request.session['tags']=[slug]
    return redirect(request.referer.split('?')[0])


def remove_tag(request, slug):
    tag_list = request.session["tags"]
    try:
        tag_list.remove(slug)
    except ValueError:
        # duplicate removal of tags
        pass
    request.session["tags"] = tag_list
    #raise Exception(request.session["tags"])
    return redirect(request.referer.split('?')[0])

imly/templates/base_account_manage.html
{% extends "base.html" %}

{% comment %}
{% block navigation %}
                
                <nav class="navbar">
                    <div class="navbar-inner">
                        <div class="container">
                            <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                                <span class="icon-bar"></span>
                            </a>
                            <a href="{% url "imly_product_list" %}" class="brand"><img src="{{ STATIC_URL }}bootstrap/img/logo.png" width="110" height="90" alt="Imly Logo"></a>
                            <div class="nav-collapse">
                                
                                <ul class="nav pull-right">
                                    <li><a href="#">What is Imly</a></li>
                                    
                                    <li><a href="#">Blog</a></li>
                                    
                                    
                                    {% if user.is_authenticated %}
                                        <li class="disabled"><a href="#"></a></li>
                                        <li class="dropdown"><a class="btn dropdown-toggle" data-toggle="dropdown" href="#">{{ user.username }} <span class="caret"></span></a>
                                            <ul class="dropdown-menu">
                                                <li><a href="{% url "imly_store_create" %}"><span class="icon-home"></span>Manage Shop</a></li>
                                                {% if user.userprofile %}
                                                    <li><a href="{% url "imly_my_profile" %}"><span class="icon-font"></span> My Account</a></li>
                                                {% else %}
                                                    <li><a href="{% url "imly_create_profile" %}"><span class="icon-font"></span> Create Account</a></li>
                                                {% endif %}
                                                <li><a href="{% url "plata_shop_cart" %}"><span class="icon-shopping-cart"></span> My Cart</a></li>
                                                <li class="divider"></li>
                                                <li><a href="#"><span class="icon-off"></span> Logout</a></li>
                                            </ul>
                                        </li>
                                    {% else %}
                                        <li class="disabled"><a href="#">|</a></li>
                                        <li><strong><a href="#">Log-In</a></strong></li>
                                    {% endif %}
                                    
                                </ul>
                            </div> <!-- end of nav-collapse div -->
                        </div><!-- end of container --> 
                    </div> <!-- end of navbar-inner --> 

                </nav> <!-- end of navbar -->               
{% endblock navigation %}
{% endcomment %}

{% block main_body %}
    
    <div class="row-fluid">
        
        <section class="span9">
            <h3>Manage Your Account</h3>
            <div class="row-fluid">
                <div class="span12">
                    <ul class="nav nav-tabs">
                    {% block manage_account_navigation %}
                    
                    {% endblock manage_account_navigation %}
                    </ul>
                </div>
            </div>
            
            {% block account_content %}
                
            {% endblock account_content %}
                
        </section>
        
        <aside class="span3">
            {% block shop_info %}
                
            {% endblock shop_info %}            
        </aside>
        

        
    </div>
{% endblock main_body %}

imly/templates/base_store_manage.html
{% extends "base.html" %}


{% block location_search_bar %}
    
{% endblock location_search_bar %}

{% block main_body %}
    <br>
    <div class="row-fluid">
        <section class="span9">
            {% block manage_store_heading %}
            <h3 style="line-height:24px;">Manage Your Shop<br><small class="muted">
            Need Help? Call +91 9920190624</small></h3>
            {% endblock manage_store_heading %}
            <br>
            <div class="row-fluid">
                <div class="span12">
                    <ul class="nav nav-tabs">
                    {% block manage_store_navigation %}
                    
                    {% endblock manage_store_navigation %}
                    </ul>
                </div>
            </div>
            
            {% block shop_content %}
                
            {% endblock shop_content %}
                
        </section>
        
        <aside class="span3">
            {% block shop_info %}
                
            {% endblock shop_info %}            
        </aside>
        

        
    </div>
{% endblock main_body %}

{% block picture_line %}
    
{% endblock picture_line %}

imly/templates/forum_base.html
{% load i18n %}<html>
<head>
<title>{% block title %}{% endblock %}</title>
<link rel="alternate" type="application/rss+xml" title="{% trans "All Latest Posts via RSS" %}" href="{% url "forum_index" %}rss/" />
<link rel="alternate" type="application/atom+xml" title="{% trans "All Latest Posts via ATOM" %}" href="{% url "forum_index" %}atom/" />
{% block extrahead %}{% endblock %}
</head>
<style type='text/css'><!--
body {
    font-family: Verdana;
    font-size: 10px;
    text-align: center;
}

#djangoForumBody {
    width: 90%;
    margin: 0 auto;
    text-align: left;
}

#djangoForumList,
#djangoForumThreadList,
#djangoForumThreadPosts {
    border-collapse: collapse;
    width: 100%;
}

#djangoForumList td,
#djangoForumThreadList td,
#djangoForumThreadPosts td {
    border: solid #777 1px;
    padding: 6px;
}

#djangoForumList .djangoForumListDetails {
    width: 70%;
}

#djangoForumList .djangoForumListDetails strong {
    font-size: 120%;
}

#djangoForumList .djangoForumListDetails .djangoForumStats {
    font-size: 80%;
}

.djangoForumListLastPost,
.djangoForumThreadLastPost {
    background-color: #ccc;
    border-bottom: solid #777 1px;
}

#djangoForumList th,
#djangoForumThreadList th,
#djangoForumThreadPosts th {
    background-color: #3a3;
    border: solid #777 1px;
    color: #fff;
    text-align: left;
    padding: 4px;
}

#djangoForumThreadPosts th {
    width: 20%;
}

#djangoForumBreadcrumbs {
    padding: 20px;
}

#djangoForumBody label {
    font-size: 110%;
    font-weight: bold;
    display: block;
    padding: 4px;
}

#djangoForumThreadPostDetail {
    width: 20%;
}
.djangoForumPagination {
    display: inline;
}
--></style>
<body>
<div id='djangoForumBody'>
<h1>{% block pagetitle %}{% trans "Welcome to the Forums" %}{% endblock %}</h1>
<div id='djangoForumBreadcrumbs'><a href='/'>{% trans "Home" %}</a> &raquo; <a href='{% url "forum_index" %}'>{% trans "Forums" %}</a>{% block breadcrumbs %}{% endblock %}</div>
{% block content %}{% endblock %}
</div>
</body>
</html>

imly/templates/no_location.html
{% extends "base.html" %}

{% block title %}Imly{% endblock title %}

{% block shop_or_product %}
    
{% endblock shop_or_product %}

{% block content %}
    <div class="span12">
        <br>
        <p class="text-center"><img src="{{ STATIC_URL }}bootstrap/img/chef_joke.png" alt="Non-existent location"></p><br>
        <h3 class="muted text-center">Haha, our food is only available in real places...</h3>
    </div>
{% endblock content %}


{% block picture_line %}

{% endblock picture_line %}

imly/templates/one_step_checkout.html
{% extends base_template|default:"base_cart.html" %}

{% load i18n plata_tags %}

{% block title %}Imly | {% trans "Checkout" %}{% endblock %}

{% block location_search_bar %}
    
{% endblock location_search_bar %}

{% block cart_content %}
    <div class="col-sm-6 col-md-7">
<h2>{% trans "Checkout" %}</h2>

<form method="post" action=".">
{% csrf_token %}
<input type="hidden" name="_checkout" value="1" />

{% form_errors orderform %}

<table class="table table-order">
<tr><td colspan="2">
<legend class="orange">{% trans "Billing address" %}</legend>
</td></tr>

{% if orderform.create_account %}
    {% form_item orderform.create_account %}
{% endif %}


{# {% form_item orderform.billing_company %} #}
{% form_item orderform.billing_first_name %}
{% form_item orderform.billing_last_name %}
{% form_item orderform.email %}
{# {% form_item orderform.billing_phone_number %} #}
{% form_item orderform.billing_address %}
{% form_item orderform.billing_phone_number %}
{% form_item orderform.billing_zip_code %}
{% form_item orderform.billing_city %}
{% form_item orderform.billing_country %}
</table>

<p><span class="shipping_same_as_billing"><span class="orange">{% trans "Shipping address" %}</span> same as billing address?{% form_item_plain orderform.shipping_same_as_billing %}</span></p>

<div class="shipping_address">
<table class="table table-order">
<tr><td colspan="2">
<legend class="orange">{% trans "Shipping address" %}</legend>
</td></tr>
{# {% form_item orderform.shipping_company %} #}
{% form_item orderform.shipping_first_name %}
{% form_item orderform.shipping_last_name %}
{# {% form_item orderform.shipping_phone_number %} #}
{% form_item orderform.shipping_address %}
{% form_item orderform.shipping_phone_number %}
{% form_item orderform.shipping_zip_code %}
{% form_item orderform.shipping_city %}
{% form_item orderform.shipping_country %}

<!-- <tr><td colspan="2">
<h2>{% trans "Notes" %}</h2>
</td></tr> -->
{# {% form_item orderform.notes %} #}
{% form_errors form %}

</table>
</div>
</div> <!-- end of span7 -->

<div class="col-sm-6 col-md-5">
{% include "plata/_order_overview.html" %}            
<p class="text-center text-muted">Pay in Cash</p>
<div class="row">
    <div class="col-md-12">    
        <button type="submit" class="btn btn-large btn-block btn-custom">{% trans "Confirm Order" %}</button>
    </div>
</div>

<div class="row">
    <br>
    <p class="text-right"><small class="text-muted">*Exact pick-up addresses will be shared after purchase</small></p>
    <br><br>
</div>


    <div class="checkout_terms_payment">
    <table class="table table-order">
    {% form_item form.terms_and_conditions %}
    {% form_item form.payment_method %}
    </table>
    </div>


</form>
</div>
{% endblock cart_content %}


{% block extra_javascript %}
<script type="text/javascript">
	$(document).ready(function(){
		if ($('#id_order-shipping_same_as_billing').is(':checked'));
		{
			$('#id_order-shipping_first_name').prop("disabled",true);
			$('#id_order-shipping_last_name').prop("disabled",true);
			$('#id_order-shipping_address').prop("disabled",true);
			$('#id_order-shipping_phone_number').prop("disabled",true);
			$('#id_order-shipping_zip_code').prop("disabled",true);
			$('#id_order-shipping_city').prop("disabled",true);
			$('#id_order-shipping_country').prop("disabled",true);
		}

		$('#id_order-shipping_same_as_billing').change(function(){
			if ($(this).is(':checked'))
			{
                                $(".shipping_address").slideUp();
				$('#id_order-shipping_first_name').prop("disabled",true);
				$('#id_order-shipping_last_name').prop("disabled",true);
				$('#id_order-shipping_address').prop("disabled",true);
				$('#id_order-shipping_phone_number').prop("disabled",true);
				$('#id_order-shipping_zip_code').prop("disabled",true);
				$('#id_order-shipping_city').prop("disabled",true);
				$('#id_order-shipping_country').prop("disabled",true);
                                return;
			}
			
                                $(".shipping_address").slideDown();
				$('#id_order-shipping_first_name').prop("disabled",false);
				$('#id_order-shipping_last_name').prop("disabled",false);
				$('#id_order-shipping_address').prop("disabled",false);
				$('#id_order-shipping_phone_number').prop("disabled",false);
				$('#id_order-shipping_zip_code').prop("disabled",false);
				$('#id_order-shipping_city').prop("disabled",false);
				$('#id_order-shipping_country').prop("disabled",false);
			
		});
		
                $("#id_order-billing_country").val("India");
                //$('#id_payment_method')[0].selectedIndex=1;
                //$("#id_terms_and_conditions").attr("checked",true);
	});
</script>            
{% endblock extra_javascript %}

imly/templates/tip.html
{% csrf_token %}
{{ tip_form.as_ul }}